/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    members: MemberAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    departments: Department;
    hubs: Hub;
    boardMembers: BoardMember;
    membershipTiers: MembershipTier;
    media: Media;
    members: Member;
    feedback: Feedback;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    hubs: HubsSelect<false> | HubsSelect<true>;
    boardMembers: BoardMembersSelect<false> | BoardMembersSelect<true>;
    membershipTiers: MembershipTiersSelect<false> | MembershipTiersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('mn' | 'en') | ('mn' | 'en')[];
  globals: {
    theme: Theme;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    theme: ThemeSelect<false> | ThemeSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'mn' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Member | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-д ашиглагдана. Хоосон орхивол гарчгаас автоматаар үүснэ.
   */
  slug: string;
  /**
   * Хэсэг нэмэх, чирж дараалал солих, устгах боломжтой.
   */
  layout?:
    | (
        | PageBannerBlock
        | SectionTabsBlock
        | RichTextBlock
        | CardGridBlock
        | QuoteBannerBlock
        | AcceleratorsBlock
        | PostsFeedBlock
        | GalleryBlock
        | ValuesListBlock
        | HistoryGridBlock
        | StatsRowBlock
        | HighlightedTextBlock
        | TimelineBlock
        | CarouselBlock
        | PeopleGridBlock
        | CreedBlock
        | SectionIntroBlock
        | DataTableBlock
        | MediaCardBlock
        | DepartmentGridBlock
        | ContactBoxBlock
        | ContactFormBlock
        | ProcessStepsBlock
        | FigureBlock
        | RegionMapBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerBlock".
 */
export interface PageBannerBlock {
  variant: 'hub' | 'vision' | 'dept' | 'deptDetail' | 'news' | 'region' | 'imageOnly' | 'hubGradient';
  overline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  tag?: string | null;
  background?: (number | null) | Media;
  /**
   * Заавал биш. Vision болон membership баннерт хэрэглэгддэг.
   */
  watermark?: (number | null) | Media;
  height?: number | null;
  align?: ('left' | 'center') | null;
  overlay?: boolean | null;
  links?:
    | {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        label?: string | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'departments';
              value: number | Department;
            } | null)
          | ({
              relationTo: 'hubs';
              value: number | Hub;
            } | null)
          | ({
              relationTo: 'membershipTiers';
              value: number | MembershipTier;
            } | null);
        url?: string | null;
        appearance?: ('default' | 'primary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Дэлгэцийн уншигчид зориулсан тайлбар.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-д ашиглагдана. Хоосон орхивол гарчгаас автоматаар үүснэ.
   */
  slug: string;
  kind: 'news' | 'article';
  publishedAt?: string | null;
  cover?: (number | null) | Media;
  /**
   * Жагсаалтын картад харагдана.
   */
  excerpt?: string | null;
  /**
   * Нийтлэлийн бие. Текст, зургийн цомог зэргийг чирж дараалуулна.
   */
  layout?:
    | (
        | PageBannerBlock
        | SectionTabsBlock
        | RichTextBlock
        | CardGridBlock
        | QuoteBannerBlock
        | AcceleratorsBlock
        | PostsFeedBlock
        | GalleryBlock
        | ValuesListBlock
        | HistoryGridBlock
        | StatsRowBlock
        | HighlightedTextBlock
        | TimelineBlock
        | CarouselBlock
        | PeopleGridBlock
        | CreedBlock
        | SectionIntroBlock
        | DataTableBlock
        | MediaCardBlock
        | DepartmentGridBlock
        | ContactBoxBlock
        | ContactFormBlock
        | ProcessStepsBlock
        | FigureBlock
        | RegionMapBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTabsBlock".
 */
export interface SectionTabsBlock {
  variant: 'dept' | 'bar' | 'cap';
  items?:
    | {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        label?: string | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'departments';
              value: number | Department;
            } | null)
          | ({
              relationTo: 'hubs';
              value: number | Hub;
            } | null)
          | ({
              relationTo: 'membershipTiers';
              value: number | MembershipTier;
            } | null);
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  align?: ('left' | 'center') | null;
  plain?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  /**
   * URL-д ашиглагдана. Хоосон орхивол гарчгаас автоматаар үүснэ.
   */
  slug: string;
  /**
   * Жагсаалт дахь дараалал.
   */
  order?: number | null;
  lead?: string | null;
  /**
   * Жагсаалтын картад харагдана.
   */
  excerpt?: string | null;
  image?: (number | null) | Media;
  layout?:
    | (
        | PageBannerBlock
        | SectionTabsBlock
        | RichTextBlock
        | CardGridBlock
        | QuoteBannerBlock
        | AcceleratorsBlock
        | PostsFeedBlock
        | GalleryBlock
        | ValuesListBlock
        | HistoryGridBlock
        | StatsRowBlock
        | HighlightedTextBlock
        | TimelineBlock
        | CarouselBlock
        | PeopleGridBlock
        | CreedBlock
        | SectionIntroBlock
        | DataTableBlock
        | MediaCardBlock
        | DepartmentGridBlock
        | ContactBoxBlock
        | ContactFormBlock
        | ProcessStepsBlock
        | FigureBlock
        | RegionMapBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('narrow' | 'wide') | null;
  background?: ('none' | 'white' | 'warm' | 'article') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  variant: 'info' | 'mission' | 'ack' | 'step';
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  items?:
    | {
        icon?: (number | null) | Media;
        badge?: string | null;
        title: string;
        text?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'departments';
                value: number | Department;
              } | null)
            | ({
                relationTo: 'hubs';
                value: number | Hub;
              } | null)
            | ({
                relationTo: 'membershipTiers';
                value: number | MembershipTier;
              } | null);
          url?: string | null;
          id?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  background?: ('warm' | 'white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubs".
 */
export interface Hub {
  id: number;
  name: string;
  /**
   * URL-д ашиглагдана. Хоосон орхивол гарчгаас автоматаар үүснэ.
   */
  slug: string;
  region?: string | null;
  layout?:
    | (
        | PageBannerBlock
        | SectionTabsBlock
        | RichTextBlock
        | CardGridBlock
        | QuoteBannerBlock
        | AcceleratorsBlock
        | PostsFeedBlock
        | GalleryBlock
        | ValuesListBlock
        | HistoryGridBlock
        | StatsRowBlock
        | HighlightedTextBlock
        | TimelineBlock
        | CarouselBlock
        | PeopleGridBlock
        | CreedBlock
        | SectionIntroBlock
        | DataTableBlock
        | MediaCardBlock
        | DepartmentGridBlock
        | ContactBoxBlock
        | ContactFormBlock
        | ProcessStepsBlock
        | FigureBlock
        | RegionMapBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBannerBlock".
 */
export interface QuoteBannerBlock {
  variant: 'quote' | 'cta' | 'dept' | 'visionGoal';
  overline?: string | null;
  title: string;
  author?: string | null;
  background?: (number | null) | Media;
  watermark?: (number | null) | Media;
  cta?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'departments';
          value: number | Department;
        } | null)
      | ({
          relationTo: 'hubs';
          value: number | Hub;
        } | null)
      | ({
          relationTo: 'membershipTiers';
          value: number | MembershipTier;
        } | null);
    url?: string | null;
    appearance?: ('default' | 'primary' | 'outline') | null;
    id?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'quoteBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membershipTiers".
 */
export interface MembershipTier {
  id: number;
  name: string;
  /**
   * URL-д ашиглагдана. Хоосон орхивол гарчгаас автоматаар үүснэ.
   */
  slug: string;
  /**
   * Жишээ нь "50,000₮ / жил". Чөлөөт текст.
   */
  price?: string | null;
  description?: string | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  layout?:
    | (
        | PageBannerBlock
        | SectionTabsBlock
        | RichTextBlock
        | CardGridBlock
        | QuoteBannerBlock
        | AcceleratorsBlock
        | PostsFeedBlock
        | GalleryBlock
        | ValuesListBlock
        | HistoryGridBlock
        | StatsRowBlock
        | HighlightedTextBlock
        | TimelineBlock
        | CarouselBlock
        | PeopleGridBlock
        | CreedBlock
        | SectionIntroBlock
        | DataTableBlock
        | MediaCardBlock
        | DepartmentGridBlock
        | ContactBoxBlock
        | ContactFormBlock
        | ProcessStepsBlock
        | FigureBlock
        | RegionMapBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AcceleratorsBlock".
 */
export interface AcceleratorsBlock {
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  items?:
    | {
        image?: (number | null) | Media;
        title: string;
        text?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'departments';
                value: number | Department;
              } | null)
            | ({
                relationTo: 'hubs';
                value: number | Hub;
              } | null)
            | ({
                relationTo: 'membershipTiers';
                value: number | MembershipTier;
              } | null);
          url?: string | null;
          id?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  numbered?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accelerators';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsFeedBlock".
 */
export interface PostsFeedBlock {
  variant: 'plain' | 'bordered' | 'related';
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  source: 'auto' | 'manual';
  limit?: number | null;
  kind?: ('all' | 'news' | 'article') | null;
  manual?: (number | Post)[] | null;
  filter?: {
    enabled?: boolean | null;
    style?: ('buttons' | 'tabs') | null;
    items?:
      | {
          label: string;
          kind: 'all' | 'news' | 'article';
          id?: string | null;
        }[]
      | null;
  };
  moreLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'departments';
          value: number | Department;
        } | null)
      | ({
          relationTo: 'hubs';
          value: number | Hub;
        } | null)
      | ({
          relationTo: 'membershipTiers';
          value: number | MembershipTier;
        } | null);
    url?: string | null;
    id?: string | null;
  };
  readLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postsFeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  variant: 'mosaic' | 'carousel' | 'grid';
  items?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesListBlock".
 */
export interface ValuesListBlock {
  title: string;
  verse?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'valuesList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HistoryGridBlock".
 */
export interface HistoryGridBlock {
  overline?: string | null;
  title: string;
  titleTone?: ('primary' | 'neutral') | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'historyGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock".
 */
export interface StatsRowBlock {
  items?:
    | {
        number: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighlightedTextBlock".
 */
export interface HighlightedTextBlock {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'highlightedText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  overline?: string | null;
  title?: string | null;
  items?:
    | {
        year: string;
        lines?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  slides?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleGridBlock".
 */
export interface PeopleGridBlock {
  variant?: ('board' | 'regionTeam') | null;
  title?: string | null;
  description?: string | null;
  source?: ('group' | 'manual') | null;
  group?: ('leadership' | 'board' | 'team' | 'region') | null;
  hub?: (number | null) | Hub;
  people?: (number | BoardMember)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'peopleGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boardMembers".
 */
export interface BoardMember {
  id: number;
  name: string;
  role?: string | null;
  photo?: (number | null) | Media;
  group: 'leadership' | 'board' | 'team' | 'region';
  department?: (number | null) | Department;
  hub?: (number | null) | Hub;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreedBlock".
 */
export interface CreedBlock {
  title: string;
  intro?: string | null;
  background?: (number | null) | Media;
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'creed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionIntroBlock".
 */
export interface SectionIntroBlock {
  title: string;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableBlock".
 */
export interface DataTableBlock {
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  variant?: ('region' | 'plain' | 'list') | null;
  /**
   * Багана бүрийн утгуудаас сонголт үүсгэнэ.
   */
  filters?:
    | {
        label: string;
        column: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Газрын зураг дээр аймаг сонгоход энэ баганаас хайна.
   */
  regionColumn?: number | null;
  columns?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        cells?:
          | {
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dataTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaCardBlock".
 */
export interface MediaCardBlock {
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DepartmentGridBlock".
 */
export interface DepartmentGridBlock {
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  source?: ('auto' | 'manual') | null;
  manual?: (number | Department)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'departmentGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBoxBlock".
 */
export interface ContactBoxBlock {
  title: string;
  personName?: string | null;
  personRole?: string | null;
  phone?: string | null;
  email?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  title: string;
  details?:
    | {
        /**
         * Жишээ: Утас, Хаяг, Цахим шуудан
         */
        label: string;
        items?:
          | {
              value: string;
              /**
               * Заавал биш. Жишээ: tel:+97690152040, mailto:info@mea.mn
               */
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  form: {
    title: string;
    nameLabel?: string | null;
    emailLabel?: string | null;
    phoneLabel?: string | null;
    messageLabel?: string | null;
    submitLabel?: string | null;
    /**
     * Амжилттай илгээсний дараа харагдана.
     */
    successMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  items?:
    | {
        number?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FigureBlock".
 */
export interface FigureBlock {
  image: number | Media;
  caption?: string | null;
  variant?: ('map' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'figure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegionMapBlock".
 */
export interface RegionMapBlock {
  header?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    align?: ('left' | 'center') | null;
  };
  /**
   * SVG доторх path ↔ аймгийн нэр.
   */
  regions?:
    | {
        pathId: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  linkToTable?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'regionMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  fullName: string;
  /**
   * /login дээр нэвтрэх нэр болно. Зөвхөн цифрээр хадгалагдана.
   */
  phone?: string | null;
  organization?: string | null;
  tier?: (number | null) | MembershipTier;
  status: 'pending' | 'approved' | 'suspended';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  name: string;
  email: string;
  phone: string;
  message: string;
  status: 'new' | 'read' | 'answered' | 'archived';
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'hubs';
        value: number | Hub;
      } | null)
    | ({
        relationTo: 'boardMembers';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'membershipTiers';
        value: number | MembershipTier;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'members';
        value: number | Member;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'members';
        value: number | Member;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        pageBanner?: T | PageBannerBlockSelect<T>;
        sectionTabs?: T | SectionTabsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        quoteBanner?: T | QuoteBannerBlockSelect<T>;
        accelerators?: T | AcceleratorsBlockSelect<T>;
        postsFeed?: T | PostsFeedBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        valuesList?: T | ValuesListBlockSelect<T>;
        historyGrid?: T | HistoryGridBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        highlightedText?: T | HighlightedTextBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        peopleGrid?: T | PeopleGridBlockSelect<T>;
        creed?: T | CreedBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        dataTable?: T | DataTableBlockSelect<T>;
        mediaCard?: T | MediaCardBlockSelect<T>;
        departmentGrid?: T | DepartmentGridBlockSelect<T>;
        contactBox?: T | ContactBoxBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        figure?: T | FigureBlockSelect<T>;
        regionMap?: T | RegionMapBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerBlock_select".
 */
export interface PageBannerBlockSelect<T extends boolean = true> {
  variant?: T;
  overline?: T;
  title?: T;
  subtitle?: T;
  tag?: T;
  background?: T;
  watermark?: T;
  height?: T;
  align?: T;
  overlay?: T;
  links?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        appearance?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTabsBlock_select".
 */
export interface SectionTabsBlockSelect<T extends boolean = true> {
  variant?: T;
  items?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        id?: T;
      };
  align?: T;
  plain?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  content?: T;
  width?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  variant?: T;
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  items?:
    | T
    | {
        icon?: T;
        badge?: T;
        title?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBannerBlock_select".
 */
export interface QuoteBannerBlockSelect<T extends boolean = true> {
  variant?: T;
  overline?: T;
  title?: T;
  author?: T;
  background?: T;
  watermark?: T;
  cta?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        appearance?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AcceleratorsBlock_select".
 */
export interface AcceleratorsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  items?:
    | T
    | {
        image?: T;
        title?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  numbered?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsFeedBlock_select".
 */
export interface PostsFeedBlockSelect<T extends boolean = true> {
  variant?: T;
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  source?: T;
  limit?: T;
  kind?: T;
  manual?: T;
  filter?:
    | T
    | {
        enabled?: T;
        style?: T;
        items?:
          | T
          | {
              label?: T;
              kind?: T;
              id?: T;
            };
      };
  moreLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
        id?: T;
      };
  readLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  variant?: T;
  items?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesListBlock_select".
 */
export interface ValuesListBlockSelect<T extends boolean = true> {
  title?: T;
  verse?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HistoryGridBlock_select".
 */
export interface HistoryGridBlockSelect<T extends boolean = true> {
  overline?: T;
  title?: T;
  titleTone?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock_select".
 */
export interface StatsRowBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighlightedTextBlock_select".
 */
export interface HighlightedTextBlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  overline?: T;
  title?: T;
  items?:
    | T
    | {
        year?: T;
        lines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        active?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleGridBlock_select".
 */
export interface PeopleGridBlockSelect<T extends boolean = true> {
  variant?: T;
  title?: T;
  description?: T;
  source?: T;
  group?: T;
  hub?: T;
  people?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreedBlock_select".
 */
export interface CreedBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  background?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionIntroBlock_select".
 */
export interface SectionIntroBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableBlock_select".
 */
export interface DataTableBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  variant?: T;
  filters?:
    | T
    | {
        label?: T;
        column?: T;
        id?: T;
      };
  regionColumn?: T;
  columns?:
    | T
    | {
        label?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        cells?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaCardBlock_select".
 */
export interface MediaCardBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DepartmentGridBlock_select".
 */
export interface DepartmentGridBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  source?: T;
  manual?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBoxBlock_select".
 */
export interface ContactBoxBlockSelect<T extends boolean = true> {
  title?: T;
  personName?: T;
  personRole?: T;
  phone?: T;
  email?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  title?: T;
  details?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              value?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  form?:
    | T
    | {
        title?: T;
        nameLabel?: T;
        emailLabel?: T;
        phoneLabel?: T;
        messageLabel?: T;
        submitLabel?: T;
        successMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  items?:
    | T
    | {
        number?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FigureBlock_select".
 */
export interface FigureBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RegionMapBlock_select".
 */
export interface RegionMapBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        align?: T;
      };
  regions?:
    | T
    | {
        pathId?: T;
        name?: T;
        id?: T;
      };
  linkToTable?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  publishedAt?: T;
  cover?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        pageBanner?: T | PageBannerBlockSelect<T>;
        sectionTabs?: T | SectionTabsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        quoteBanner?: T | QuoteBannerBlockSelect<T>;
        accelerators?: T | AcceleratorsBlockSelect<T>;
        postsFeed?: T | PostsFeedBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        valuesList?: T | ValuesListBlockSelect<T>;
        historyGrid?: T | HistoryGridBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        highlightedText?: T | HighlightedTextBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        peopleGrid?: T | PeopleGridBlockSelect<T>;
        creed?: T | CreedBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        dataTable?: T | DataTableBlockSelect<T>;
        mediaCard?: T | MediaCardBlockSelect<T>;
        departmentGrid?: T | DepartmentGridBlockSelect<T>;
        contactBox?: T | ContactBoxBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        figure?: T | FigureBlockSelect<T>;
        regionMap?: T | RegionMapBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  lead?: T;
  excerpt?: T;
  image?: T;
  layout?:
    | T
    | {
        pageBanner?: T | PageBannerBlockSelect<T>;
        sectionTabs?: T | SectionTabsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        quoteBanner?: T | QuoteBannerBlockSelect<T>;
        accelerators?: T | AcceleratorsBlockSelect<T>;
        postsFeed?: T | PostsFeedBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        valuesList?: T | ValuesListBlockSelect<T>;
        historyGrid?: T | HistoryGridBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        highlightedText?: T | HighlightedTextBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        peopleGrid?: T | PeopleGridBlockSelect<T>;
        creed?: T | CreedBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        dataTable?: T | DataTableBlockSelect<T>;
        mediaCard?: T | MediaCardBlockSelect<T>;
        departmentGrid?: T | DepartmentGridBlockSelect<T>;
        contactBox?: T | ContactBoxBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        figure?: T | FigureBlockSelect<T>;
        regionMap?: T | RegionMapBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubs_select".
 */
export interface HubsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  layout?:
    | T
    | {
        pageBanner?: T | PageBannerBlockSelect<T>;
        sectionTabs?: T | SectionTabsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        quoteBanner?: T | QuoteBannerBlockSelect<T>;
        accelerators?: T | AcceleratorsBlockSelect<T>;
        postsFeed?: T | PostsFeedBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        valuesList?: T | ValuesListBlockSelect<T>;
        historyGrid?: T | HistoryGridBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        highlightedText?: T | HighlightedTextBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        peopleGrid?: T | PeopleGridBlockSelect<T>;
        creed?: T | CreedBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        dataTable?: T | DataTableBlockSelect<T>;
        mediaCard?: T | MediaCardBlockSelect<T>;
        departmentGrid?: T | DepartmentGridBlockSelect<T>;
        contactBox?: T | ContactBoxBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        figure?: T | FigureBlockSelect<T>;
        regionMap?: T | RegionMapBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boardMembers_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  group?: T;
  department?: T;
  hub?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membershipTiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  price?: T;
  description?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  layout?:
    | T
    | {
        pageBanner?: T | PageBannerBlockSelect<T>;
        sectionTabs?: T | SectionTabsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        quoteBanner?: T | QuoteBannerBlockSelect<T>;
        accelerators?: T | AcceleratorsBlockSelect<T>;
        postsFeed?: T | PostsFeedBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        valuesList?: T | ValuesListBlockSelect<T>;
        historyGrid?: T | HistoryGridBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        highlightedText?: T | HighlightedTextBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        peopleGrid?: T | PeopleGridBlockSelect<T>;
        creed?: T | CreedBlockSelect<T>;
        sectionIntro?: T | SectionIntroBlockSelect<T>;
        dataTable?: T | DataTableBlockSelect<T>;
        mediaCard?: T | MediaCardBlockSelect<T>;
        departmentGrid?: T | DepartmentGridBlockSelect<T>;
        contactBox?: T | ContactBoxBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        figure?: T | FigureBlockSelect<T>;
        regionMap?: T | RegionMapBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  organization?: T;
  tier?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  primary: string;
  primaryDark: string;
  primaryLight: string;
  neutral0: string;
  neutral50: string;
  neutral100: string;
  neutral150: string;
  neutral200: string;
  neutral300: string;
  neutral400: string;
  neutral500: string;
  neutral600: string;
  neutral700: string;
  neutral800: string;
  neutral900: string;
  borderMedium: string;
  accentRed: string;
  link: string;
  fontDisplay: 'playfair' | 'manrope' | 'inter';
  fontBody: 'playfair' | 'manrope' | 'inter';
  fontUi: 'playfair' | 'manrope' | 'inter';
  textDisplay: string;
  textH1: string;
  textH2: string;
  textH3: string;
  textH4: string;
  textBody: string;
  textSm: string;
  textCaption: string;
  sectionPad: string;
  gutter: string;
  containerMax: string;
  radiusSm: string;
  radiusMd: string;
  radiusLg: string;
  radius2xl: string;
  radiusFull: string;
  paddingMd: string;
  paddingLg: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  announcement?: {
    enabled?: boolean | null;
    /**
     * Жишээ: ЗАРЛАЛ: "Ээлжит бага хурал 2025.10.09-10нд УБ-д
     */
    text?: string | null;
    cta?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'departments';
            value: number | Department;
          } | null)
        | ({
            relationTo: 'hubs';
            value: number | Hub;
          } | null)
        | ({
            relationTo: 'membershipTiers';
            value: number | MembershipTier;
          } | null);
      url?: string | null;
      id?: string | null;
    };
    links?:
      | {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'departments';
                value: number | Department;
              } | null)
            | ({
                relationTo: 'hubs';
                value: number | Hub;
              } | null)
            | ({
                relationTo: 'membershipTiers';
                value: number | MembershipTier;
              } | null);
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    showLanguageSwitcher?: boolean | null;
  };
  header?: {
    logo?: (number | null) | Media;
    nav?:
      | {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'departments';
                value: number | Department;
              } | null)
            | ({
                relationTo: 'hubs';
                value: number | Hub;
              } | null)
            | ({
                relationTo: 'membershipTiers';
                value: number | MembershipTier;
              } | null);
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    showSearch?: boolean | null;
    loginLink?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      label?: string | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'departments';
            value: number | Department;
          } | null)
        | ({
            relationTo: 'hubs';
            value: number | Hub;
          } | null)
        | ({
            relationTo: 'membershipTiers';
            value: number | MembershipTier;
          } | null);
      url?: string | null;
      id?: string | null;
    };
  };
  newsletter?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
  };
  footer?: {
    logo?: (number | null) | Media;
    topLinks?:
      | {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'departments';
                value: number | Department;
              } | null)
            | ({
                relationTo: 'hubs';
                value: number | Hub;
              } | null)
            | ({
                relationTo: 'membershipTiers';
                value: number | MembershipTier;
              } | null);
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    contact?: {
      title?: string | null;
      items?:
        | {
            value: string;
            /**
             * Заавал биш. Жишээ: mailto:info@mea.mn
             */
            href?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    navGroups?:
      | {
          title: string;
          links?:
            | {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                label?: string | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'departments';
                      value: number | Department;
                    } | null)
                  | ({
                      relationTo: 'hubs';
                      value: number | Hub;
                    } | null)
                  | ({
                      relationTo: 'membershipTiers';
                      value: number | MembershipTier;
                    } | null);
                url?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Хөлийн доод эгнээний голд дугуй товч болж харагдана.
     */
    socialLinks?:
      | {
          platform: 'facebook' | 'instagram' | 'youtube';
          url: string;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
    legalLinks?:
      | {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'departments';
                value: number | Department;
              } | null)
            | ({
                relationTo: 'hubs';
                value: number | Hub;
              } | null)
            | ({
                relationTo: 'membershipTiers';
                value: number | MembershipTier;
              } | null);
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  auth?: {
    login?: {
      title?: string | null;
      identifierLabel?: string | null;
      /**
       * Утасны дугаар эсвэл и-мэйлээр нэвтэрч болно.
       */
      identifierPlaceholder?: string | null;
      passwordLabel?: string | null;
      passwordPlaceholder?: string | null;
      submitLabel?: string | null;
      dividerLabel?: string | null;
      forgotLink?: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        label?: string | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'departments';
              value: number | Department;
            } | null)
          | ({
              relationTo: 'hubs';
              value: number | Hub;
            } | null)
          | ({
              relationTo: 'membershipTiers';
              value: number | MembershipTier;
            } | null);
        url?: string | null;
        id?: string | null;
      };
      registerLink?: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        label?: string | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'departments';
              value: number | Department;
            } | null)
          | ({
              relationTo: 'hubs';
              value: number | Hub;
            } | null)
          | ({
              relationTo: 'membershipTiers';
              value: number | MembershipTier;
            } | null);
        url?: string | null;
        id?: string | null;
      };
      backLink?: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        label?: string | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'departments';
              value: number | Department;
            } | null)
          | ({
              relationTo: 'hubs';
              value: number | Hub;
            } | null)
          | ({
              relationTo: 'membershipTiers';
              value: number | MembershipTier;
            } | null);
        url?: string | null;
        id?: string | null;
      };
    };
    profile?: {
      /**
       * Нэвтэрсэн үед толгойн товч дээр гарах текст.
       */
      headerLinkLabel?: string | null;
      /**
       * {name} нь хэрэглэгчийн нэрээр солигдоно.
       */
      greeting?: string | null;
      menuAccountLabel?: string | null;
      menuLogoutLabel?: string | null;
      panelTitle?: string | null;
      editLabel?: string | null;
      generalTitle?: string | null;
      phoneLabel?: string | null;
      emailLabel?: string | null;
      passwordTitle?: string | null;
      passwordEditLabel?: string | null;
      passwordFieldLabel?: string | null;
      passwordCurrentLabel?: string | null;
      passwordNewLabel?: string | null;
      passwordConfirmLabel?: string | null;
      passwordSubmitLabel?: string | null;
      passwordCancelLabel?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  primary?: T;
  primaryDark?: T;
  primaryLight?: T;
  neutral0?: T;
  neutral50?: T;
  neutral100?: T;
  neutral150?: T;
  neutral200?: T;
  neutral300?: T;
  neutral400?: T;
  neutral500?: T;
  neutral600?: T;
  neutral700?: T;
  neutral800?: T;
  neutral900?: T;
  borderMedium?: T;
  accentRed?: T;
  link?: T;
  fontDisplay?: T;
  fontBody?: T;
  fontUi?: T;
  textDisplay?: T;
  textH1?: T;
  textH2?: T;
  textH3?: T;
  textH4?: T;
  textBody?: T;
  textSm?: T;
  textCaption?: T;
  sectionPad?: T;
  gutter?: T;
  containerMax?: T;
  radiusSm?: T;
  radiusMd?: T;
  radiusLg?: T;
  radius2xl?: T;
  radiusFull?: T;
  paddingMd?: T;
  paddingLg?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
        links?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
        showLanguageSwitcher?: T;
      };
  header?:
    | T
    | {
        logo?: T;
        nav?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
        showSearch?: T;
        loginLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        placeholder?: T;
        buttonLabel?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        topLinks?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    href?: T;
                    id?: T;
                  };
            };
        navGroups?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        copyright?: T;
        legalLinks?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
              id?: T;
            };
      };
  auth?:
    | T
    | {
        login?:
          | T
          | {
              title?: T;
              identifierLabel?: T;
              identifierPlaceholder?: T;
              passwordLabel?: T;
              passwordPlaceholder?: T;
              submitLabel?: T;
              dividerLabel?: T;
              forgotLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    id?: T;
                  };
              registerLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    id?: T;
                  };
              backLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                    id?: T;
                  };
            };
        profile?:
          | T
          | {
              headerLinkLabel?: T;
              greeting?: T;
              menuAccountLabel?: T;
              menuLogoutLabel?: T;
              panelTitle?: T;
              editLabel?: T;
              generalTitle?: T;
              phoneLabel?: T;
              emailLabel?: T;
              passwordTitle?: T;
              passwordEditLabel?: T;
              passwordFieldLabel?: T;
              passwordCurrentLabel?: T;
              passwordNewLabel?: T;
              passwordConfirmLabel?: T;
              passwordSubmitLabel?: T;
              passwordCancelLabel?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * YouTube-ийн хаягийг буулгана уу. Ж: https://www.youtube.com/watch?v=… эсвэл https://youtu.be/…
   */
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}