import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_pages_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_pages_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_pages_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__pages_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__pages_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__pages_v_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__pages_v_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_posts_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_posts_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_posts_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_posts_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_posts_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__posts_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__posts_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__posts_v_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__posts_v_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__posts_v_version_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_departments_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_departments_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_departments_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_departments_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__departments_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__departments_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__departments_v_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__departments_v_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_hubs_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_hubs_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_hubs_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_hubs_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__hubs_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__hubs_v_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum__hubs_v_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum__hubs_v_blocks_posts_feed_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind" ADD VALUE 'prayer';
  ALTER TYPE "public"."enum_membership_tiers_blocks_posts_feed_kind" ADD VALUE 'newsArticle' BEFORE 'news';
  ALTER TYPE "public"."enum_membership_tiers_blocks_posts_feed_kind" ADD VALUE 'prayer';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_pages_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum_pages_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "pages_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_pages_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "pages_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_pages_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum_pages_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "pages_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_pages_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum_pages_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "pages_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_pages_blocks_posts_feed_kind";
  ALTER TABLE "pages_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_pages_blocks_posts_feed_kind" USING "kind"::"public"."enum_pages_blocks_posts_feed_kind";
  ALTER TABLE "_pages_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__pages_v_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum__pages_v_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_pages_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__pages_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_pages_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__pages_v_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum__pages_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_pages_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__pages_v_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum__pages_v_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_pages_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__pages_v_blocks_posts_feed_kind";
  ALTER TABLE "_pages_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__pages_v_blocks_posts_feed_kind" USING "kind"::"public"."enum__pages_v_blocks_posts_feed_kind";
  ALTER TABLE "posts_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_posts_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum_posts_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "posts_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_posts_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "posts_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_posts_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum_posts_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "posts_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_posts_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum_posts_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "posts_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_posts_blocks_posts_feed_kind";
  ALTER TABLE "posts_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_posts_blocks_posts_feed_kind" USING "kind"::"public"."enum_posts_blocks_posts_feed_kind";
  ALTER TABLE "posts" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "posts" ALTER COLUMN "kind" SET DEFAULT 'news'::text;
  DROP TYPE "public"."enum_posts_kind";
  CREATE TYPE "public"."enum_posts_kind" AS ENUM('news', 'article');
  ALTER TABLE "posts" ALTER COLUMN "kind" SET DEFAULT 'news'::"public"."enum_posts_kind";
  ALTER TABLE "posts" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_posts_kind" USING "kind"::"public"."enum_posts_kind";
  ALTER TABLE "_posts_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__posts_v_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum__posts_v_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_posts_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__posts_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_posts_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__posts_v_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum__posts_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_posts_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__posts_v_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum__posts_v_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_posts_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__posts_v_blocks_posts_feed_kind";
  ALTER TABLE "_posts_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__posts_v_blocks_posts_feed_kind" USING "kind"::"public"."enum__posts_v_blocks_posts_feed_kind";
  ALTER TABLE "_posts_v" ALTER COLUMN "version_kind" SET DATA TYPE text;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_kind" SET DEFAULT 'news'::text;
  DROP TYPE "public"."enum__posts_v_version_kind";
  CREATE TYPE "public"."enum__posts_v_version_kind" AS ENUM('news', 'article');
  ALTER TABLE "_posts_v" ALTER COLUMN "version_kind" SET DEFAULT 'news'::"public"."enum__posts_v_version_kind";
  ALTER TABLE "_posts_v" ALTER COLUMN "version_kind" SET DATA TYPE "public"."enum__posts_v_version_kind" USING "version_kind"::"public"."enum__posts_v_version_kind";
  ALTER TABLE "departments_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "departments_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_departments_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum_departments_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "departments_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_departments_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "departments_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_departments_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum_departments_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "departments_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "departments_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_departments_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum_departments_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "departments_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_departments_blocks_posts_feed_kind";
  ALTER TABLE "departments_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_departments_blocks_posts_feed_kind" USING "kind"::"public"."enum_departments_blocks_posts_feed_kind";
  ALTER TABLE "_departments_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_departments_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__departments_v_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum__departments_v_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_departments_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__departments_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_departments_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__departments_v_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum__departments_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_departments_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_departments_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__departments_v_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum__departments_v_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_departments_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__departments_v_blocks_posts_feed_kind";
  ALTER TABLE "_departments_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__departments_v_blocks_posts_feed_kind" USING "kind"::"public"."enum__departments_v_blocks_posts_feed_kind";
  ALTER TABLE "hubs_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "hubs_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_hubs_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum_hubs_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "hubs_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_hubs_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "hubs_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_hubs_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum_hubs_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "hubs_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "hubs_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_hubs_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum_hubs_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "hubs_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_hubs_blocks_posts_feed_kind";
  ALTER TABLE "hubs_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_hubs_blocks_posts_feed_kind" USING "kind"::"public"."enum_hubs_blocks_posts_feed_kind";
  ALTER TABLE "_hubs_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_hubs_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__hubs_v_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum__hubs_v_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_hubs_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__hubs_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_hubs_v_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__hubs_v_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum__hubs_v_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "_hubs_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_hubs_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum__hubs_v_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum__hubs_v_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "_hubs_v_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum__hubs_v_blocks_posts_feed_kind";
  ALTER TABLE "_hubs_v_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__hubs_v_blocks_posts_feed_kind" USING "kind"::"public"."enum__hubs_v_blocks_posts_feed_kind";
  ALTER TABLE "membership_tiers_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "membership_tiers_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind";
  CREATE TYPE "public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "membership_tiers_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "membership_tiers_blocks_posts_feed_filter_items" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind" USING "kind"::"public"."enum_membership_tiers_blocks_posts_feed_filter_items_kind";
  ALTER TABLE "membership_tiers_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "membership_tiers_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::text;
  DROP TYPE "public"."enum_membership_tiers_blocks_posts_feed_kind";
  CREATE TYPE "public"."enum_membership_tiers_blocks_posts_feed_kind" AS ENUM('all', 'news', 'article');
  ALTER TABLE "membership_tiers_blocks_posts_feed" ALTER COLUMN "kind" SET DEFAULT 'all'::"public"."enum_membership_tiers_blocks_posts_feed_kind";
  ALTER TABLE "membership_tiers_blocks_posts_feed" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_membership_tiers_blocks_posts_feed_kind" USING "kind"::"public"."enum_membership_tiers_blocks_posts_feed_kind";`)
}
